version: "3.8"

# Example
services:
  home:
    image: giterhub/slender:latest
    container_name: slender-home
    restart: unless-stopped
    network_mode: bridge
    environment:
      - "SLENDER_ACCESS_PWD=123456"
      - "SLENDER_ADMIN_PWD=abcdef"
      - "SLENDER_LOG_LEVEL=ERROR"
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/slender/data:/app/data
