name: Only Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HTTP_PROXY: ${{ vars.PROXY }}
      HTTPS_PROXY: ${{ vars.PROXY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Get git tags
        id: git_tags
        run: |
          current=$(git describe --abbrev=0 --tags)
          echo "current=${current}" >> ${GITHUB_OUTPUT}
          prev=$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)
          echo "prev=${prev}" >> ${GITHUB_OUTPUT}
      - name: Create changelog text
        id: changelog_text
        uses: dragonish/tag-changelog@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          config_file: ../.gitea/scripts/tag-changelog-config.cjs
      - name: Create release
        uses: akkuman/gitea-release-action@v1
        env:
          NODE_OPTIONS: '--experimental-fetch' # if nodejs < 18
        with:
          server_url: ${{ vars.SERVER }}
          files: |-
            dist/**
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ steps.git_tags.outputs.current }}
          body: |
            ${{ steps.changelog_text.outputs.changes }}

            ---

            ## Details

            See: [${{ steps.git_tags.outputs.prev }}...${{ steps.git_tags.outputs.current }}](/compare/${{ steps.git_tags.outputs.prev }}...${{ steps.git_tags.outputs.current }}).
      - name: Send notification
        if: ${{ !cancelled() && secrets.NTFY_URL != '' && secrets.NTFY_TOPIC != '' && secrets.NTFY_TOKEN != '' }}
        uses: dragonish/send-to-ntfy@v1
        with:
          base-url: ${{ secrets.NTFY_URL }}
          topic: ${{ secrets.NTFY_TOPIC }}
          access-token: ${{ secrets.NTFY_TOKEN }}
          title: ${{ gitea.repository }}
          message: "Release ${{ steps.git_tags.outputs.current }}"
          tags: "tea,release,${{ job.status }}"
          priority: 2
          click: "${{ vars.WEB_SERVER }}/${{ gitea.repository }}/releases/tag/${{ steps.git_tags.outputs.current }}"
