name: Only Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HTTP_PROXY: ${{ vars.PROXY }}
      HTTPS_PROXY: ${{ vars.PROXY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Get git tags
        id: git_tags
        run: |
          current=$(git describe --abbrev=0 --tags)
          echo "current=${current}" >> ${GITHUB_OUTPUT}
          prev=$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)
          echo "prev=${prev}" >> ${GITHUB_OUTPUT}
      - name: Create changelog text
        id: changelog_text
        uses: dragonish/tag-changelog@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          config_file: ../.gitea/scripts/tag-changelog-config.cjs
      - name: Create release
        uses: akkuman/gitea-release-action@v1
        env:
          NODE_OPTIONS: '--experimental-fetch' # if nodejs < 18
        with:
          server_url: ${{ vars.SERVER }}
          files: |-
            dist/**
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ steps.git_tags.outputs.current }}
          body: |
            ${{ steps.changelog_text.outputs.changes }}

            ## Icons

            | Name | Version |
            | ---- | :-----: |
            | [MaterialDesign](https://github.com/Templarian/MaterialDesign) | ${{ steps.icons.outputs.mdi_version }} |
            | [simple-icons](https://github.com/simple-icons/simple-icons) | ${{ steps.icons.outputs.si_version }} |

            ---

            ## Details

            See: [${{ steps.git_tags.outputs.prev }}...${{ steps.git_tags.outputs.current }}](/compare/${{ steps.git_tags.outputs.prev }}...${{ steps.git_tags.outputs.current }}).
      - name: Send notification
        if: ${{ !cancelled() && secrets.GOTIFY_URL != '' && secrets.GOTIFY_TOKEN != '' }}
        uses: dragonish/send-to-gotify@v1
        with:
          url: ${{ secrets.GOTIFY_URL }}
          token: ${{ secrets.GOTIFY_TOKEN }}
          title: ${{ gitea.repository }}
          message: "Release ${{ steps.git_tags.outputs.current }}\n\n*status: ${{ job.status }}*"
          content-type: 'text/markdown'
