FROM golang:alpine AS builder

RUN echo "Asia/Shanghai" > /etc/timezone
RUN apk add git bash gcc musl-dev upx
ENV TZ=Asia/Shanghai
RUN apk add tzdata && \
  cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app

ENV GO111MODULE=on
ENV CGO_ENABLED=1
ENV GOPROXY=https://goproxy.cn
COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
