name: Latest Build

on:
  workflow_dispatch:
  repository_dispatch:
    types: [pr-merged]

env:
  DOCKERHUB_REPO: giterhub/slender

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download icons
        id: icons
        run: |
          mdi_json="./assets/material-design-icons/index.json"
          si_json="./assets/simple-icons/index.json"
          curl -o $mdi_json https://registry.npmjs.org/@mdi/js/latest
          curl -o ./assets/material-design-icons/index.js https://gcore.jsdelivr.net/npm/@mdi/js@latest/mdi.js
          curl -o $si_json https://registry.npmjs.org/simple-icons/latest
          curl -o ./assets/simple-icons/index.js https://gcore.jsdelivr.net/npm/simple-icons@latest/index.js
      - name: Generate app version
        run: |
          echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV
          github_sha=${{ github.sha }}
          echo APP_COMMIT=${github_sha:0:7} >> $GITHUB_ENV
      - name: Download manager
        id: download_manager
        uses: robinraju/release-downloader@v1.10
        with:
          repository: "dragonish/slender-manager"
          latest: true
          fileName: "*.zip"
          tarBall: false
          zipBall: false
          out-file-path: act-downloads
      - name: Unzip manager
        run: |
          unzip ./act-downloads/slender-manager_${{ steps.download_manager.outputs.tag_name }}.zip -d ./web/manager
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        if: success()
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          build-args: |
            VERSION="${{ env.APP_VERSION }}"
            COMMIT="${{ env.APP_COMMIT }}"
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
          platforms: |
            linux/amd64
            linux/386
            linux/arm64
