name: Release

on:
  push:
    tags:
      - '*'

env:
  DOCKERHUB_REPO: giterhub/slender

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download icons
        id: icons
        run: |
          mdi_json="./assets/material-design-icons/index.json"
          si_json="./assets/simple-icons/index.json"
          curl -o $mdi_json https://registry.npmjs.org/@mdi/js/latest
          curl -o ./assets/material-design-icons/index.js https://gcore.jsdelivr.net/npm/@mdi/js@latest/mdi.js
          curl -o $si_json https://registry.npmjs.org/simple-icons/latest
          curl -o ./assets/simple-icons/index.js https://gcore.jsdelivr.net/npm/simple-icons@latest/index.js
          mdi_version=$(cat $mdi_json | jq -r '.version')
          si_version=$(cat $si_json | jq -r '.version')
          echo "mdi_version=${mdi_version}" >> $GITHUB_OUTPUT
          echo "si_version=${si_version}" >> $GITHUB_OUTPUT
      - name: Generate app version
        run: |
          echo APP_VERSION=`git describe --tags --abbrev=0` >> $GITHUB_ENV
          github_sha=${{ github.sha }}
          echo APP_COMMIT=${github_sha:0:7} >> $GITHUB_ENV
      - name: Create changelog text
        id: changelog_text
        uses: dragonish/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/scripts/tag-changelog-config.cjs
      - name: Download manager
        id: download_manager
        uses: robinraju/release-downloader@v1.10
        with:
          repository: "dragonish/slender-manager"
          latest: true
          fileName: "*.zip"
          tarBall: false
          zipBall: false
          out-file-path: act-downloads
      - name: Unzip manager
        run: |
          unzip ./act-downloads/slender-manager_${{ steps.download_manager.outputs.tag_name }}.zip -d ./web/manager
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        if: success()
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          build-args: |
            VERSION=${{ env.APP_VERSION }}
            COMMIT=${{ env.APP_COMMIT }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}
          platforms: |
            linux/amd64
            linux/386
            linux/arm64
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ env.APP_VERSION }}
          prerelease: false
          draft: false
          body: |
            ${{ steps.changelog_text.outputs.changes }}

            ## Manager Changelog

            See: [dragonish/slender-manager](https://github.com/dragonish/slender-manager/releases)

            ## Icons

            | Name | Version |
            | ---- | :-----: |
            | [MaterialDesign](https://github.com/Templarian/MaterialDesign) | ${{ steps.icons.outputs.mdi_version }} |
            | [simple-icons](https://github.com/simple-icons/simple-icons) | ${{ steps.icons.outputs.si_version }} |

            ## Docker image

            - [giterhub/slender](https://hub.docker.com/r/giterhub/slender)
